### ISSUE TITLE
need to create table inside the db 

### ISSUE THREAD

**Issue by shubham1091** [FrancescoXX/fullstack-next-node-postgres#1]
we need to create a table inside the Postgres database from the schema after the db and backend are up and running other we will get an error when we request the backend to create, update, delete a user cuz we don't have a table inside the db container

here is my solution we can remove 'CMD' to run the server form [backend.dockerfile](https://github.com/FrancescoXX/fullstack-next-node-postgres/blob/main/backend/backend.dockerfile) and this command inside [compose.yaml](https://github.com/FrancescoXX/fullstack-next-node-postgres/blob/main/compose.yaml) file

```yaml
command: sh -c "npm run start && npx prisma migrate dev --name init"
depends_on:
         - db
```
